### ISSUE TITLE
模型文件和checkpoint文件不匹配

### ISSUE THREAD

**Issue by iaoxuesheng** [JoshuaChou2018/MedAGI#2]
Traceback (most recent call last):
  File "D:\conda\envs\medagi\lib\site-packages\gradio\routes.py", line 393, in run_predict
    output = await app.get_blocks().process_api(
  File "D:\conda\envs\medagi\lib\site-packages\gradio\blocks.py", line 1108, in process_api
    result = await self.call_function(
  File "D:\conda\envs\medagi\lib\site-packages\gradio\blocks.py", line 915, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "D:\conda\envs\medagi\lib\site-packages\anyio\to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "D:\conda\envs\medagi\lib\site-packages\anyio\_backends\_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "D:\conda\envs\medagi\lib\site-packages\anyio\_backends\_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "F:\MedAGI\demo.py", line 103, in gradio_answer
    llm_message = chat.answer(conv=chat_state,
  File "F:\MedAGI\medagi\conversation\conversation.py", line 145, in answer
    image_emb, _ = self.model.encode_img(img_list[-1],message,cfg)
  File "F:\MedAGI\medagi\models\medagi.py", line 164, in encode_img
    msg = self.load_state_dict(ckpt['model'], strict=False)
  File "D:\conda\envs\medagi\lib\site-packages\torch\nn\modules\module.py", line 1667, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for MedAGI:
        size mismatch for llama_proj.weight: copying a param with shape torch.Size([5120, 768]) from checkpoint, the shape in current model is torch.Size([4096, 768]).
        size mismatch for llama_proj.bias: copying a param with shape torch.Size([5120]) from checkpoint, the shape in current model is torch.Size([4096]).

**Comment by JoshuaChou2018** [comment]
Hi，根据错误信息显示投影层的模型尺寸不匹配，请检查您模型参数的尺寸，因为我们在本项目中没有公开文中提到的3个模型参数。

**Comment by iaoxuesheng** [comment]
我用的是您的那个Skingpt_v1模型参数，只用了这一个，模型用的vicuna_7b




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "JoshuaChou2018/MedAGI"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年9月7日(星期四) 晚上10:02
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [JoshuaChou2018/MedAGI] 模型文件和checkpoint文件不匹配 (Issue #2)





 
Hi，根据错误信息显示投影层的模型尺寸不匹配，请检查您模型参数的尺寸，因为我们在本项目中没有公开文中提到的3个模型参数。

**Comment by JoshuaChou2018** [comment]
Hi，Skingpt_v1对此模型不适用，我们在文中测试的版本为skingpt_v4.2.pth（非公开版本），如果您对我们的工作感兴趣可以参考README中的训练流程训练特定domain的模型

**Comment by iaoxuesheng** [comment]
这样啊，我是研究生初学者，想在学校研究简单使用，那三个文件您方便分享一下嘛




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "JoshuaChou2018/MedAGI"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年9月7日(星期四) 晚上11:08
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [JoshuaChou2018/MedAGI] 模型文件和checkpoint文件不匹配 (Issue #2)





 
Hi，Skingpt_v1对此模型不适用，我们在文中测试的版本为skingpt_v4.2.pth

**Comment by JoshuaChou2018** [comment]
请参考 #1 , 由于这三个模型都存在一些版权和隐私问题，我们无法在本项目中公开模型。但是我们在 #1 中提供了三个模型的具体来源，可以参考自行训练模型。

**Comment by iaoxuesheng** [comment]
可以加您的私人邮箱嘛

**Comment by JoshuaChou2018** [comment]
Hi 有其它需求可以邮件联系 juexiao.zhou@kaust.edu.sa
